version: '3.8'
services:
  kafka1:
    image: bitnami/kafka
    container_name: kafka-1
    #hostname: kafka-1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092 #указать внешний IP / пробросить порты на 9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097 #указать внешние порты для кафка 2 и 3
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      #- KAFKA_BROKER_ID=1
      #- KAFKA_CFG_LOG_DIRS=/bitnami/logs
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OETBNTcwNTJENDM2Qk
    volumes:
      - ./kafka/kafka_1_data:/bitnami/kafka

  kafka2:
    image: bitnami/kafka
    container_name: kafka-2
    #hostname: kafka-2
    ports:
      - "9094:9094" #ports
      - "9095:9095"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9094 #указать внешний IP / пробросить порты на 9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      #- KAFKA_BROKER_ID=2
      #- KAFKA_CFG_LOG_DIRS=/bitnami/logs
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OETBNTcwNTJENDM2Qk
    volumes:
      - ./kafka/kafka_2_data:/bitnami/kafka

  kafka3:
    image: bitnami/kafka
    container_name: kafka-3
    #hostname: kafka3
    ports:
      - "9096:9096" #ports
      - "9097:9097"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9096,CONTROLLER://:9097
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9096 #указать внешний IP / пробросить порты на 9096
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9095,3@kafka-3:9097
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=3
      #- KAFKA_BROKER_ID=3
      #- KAFKA_CFG_LOG_DIRS=/bitnami/logs
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OETBNTcwNTJENDM2Qk
    volumes:
      - ./kafka/kafka_3_data:/bitnami/kafka

  ui:
    image: provectuslabs/kafka-ui:v0.4.0
    ports:
      - "8085:8080"
    #depends_on:
    #  - kafka1
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9094,kafka2:9096
      - KAFKA_CLUSTERS_0_NAME=kraft-test-cluster

#volumes:
#  kafka_1_data:
#    driver: local
#  kafka_2_data:
#    driver: local
#  kafka_3_data:
#    driver: local