server:
  port: 9091

application:
  kafka:
    user-created-topic: user-created-event-topic

spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:19094
    consumer:
      bootstrap-servers: localhost:19092,localhost:19094
      group-id: unique-group-id
      client-id: event-consumer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_main
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss