server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_main
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

    #url: ${SPRING_DATASOURCE_URL}
    #username: ${POSTGRES_USER}
    #password: ${POSTGRES_PASSWORD}